version: "3"
services:
  rabbitmq:
     image: rabbitmq:3.9.3-management-alpine
     ports:
     - 5672:5672
     - 15672:15672
     volumes:
     - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/ShopApp
     - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq/ShopApp
     networks:
     - rabbitmq_go_net
    

 
networks:
  rabbitmq_go_net:
    driver: bridge
